import {
  Sertifikat,
  User,
  ProfileData,
  AppSettings,
  GoogleSheetsSettings,
  CertificateTemplate,
  CertificateLayout,
  CertificatePreviewData,
} from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin',
    email: 'admin@gmail.com',
    createdAt: new Date().toISOString(),
  },
];

export const mockSertifikats: Sertifikat[] = [
  {
    id: '1',
    nama: 'Ahmad Suryanto',
    nomor_sertif: 'CERT-2024-001',
    asal: 'PT ABC Indonesia',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    nama: 'Budi Hartono',
    nomor_sertif: 'CERT-2024-002',
    asal: 'CV Teknologi Maju',
    kab_kot: 'Malang',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    id: '3',
    nama: 'Citra Dewi',
    nomor_sertif: 'CERT-2024-003',
    asal: 'Universitas Airlangga',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    id: '4',
    nama: 'Dudi Mahmud',
    nomor_sertif: 'CERT-2024-004',
    asal: 'PT Global Services',
    kab_kot: 'Gresik',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    id: '5',
    nama: 'Eka Putra',
    nomor_sertif: 'CERT-2024-005',
    asal: 'PT Digital Solutions',
    kab_kot: 'Sidoarjo',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-19',
    updatedAt: '2024-01-19',
  },
  {
    id: '6',
    nama: 'Fitrah Yusuf',
    nomor_sertif: 'CERT-2024-006',
    asal: 'Kementerian Pendidikan',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '7',
    nama: 'Gita Sari',
    nomor_sertif: 'CERT-2024-007',
    asal: 'PT Konsultan Bisnis',
    kab_kot: 'Lamongan',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-21',
    updatedAt: '2024-01-21',
  },
  {
    id: '8',
    nama: 'Hendra Wijaya',
    nomor_sertif: 'CERT-2024-008',
    asal: 'BUMN Jasa Konstruksi',
    kab_kot: 'Mojokerto',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-22',
    updatedAt: '2024-01-22',
  },
  {
    id: '9',
    nama: 'Irma Salsabila',
    nomor_sertif: 'CERT-2024-009',
    asal: 'PT Energi Terbarukan',
    kab_kot: 'Tuban',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-01-23',
    updatedAt: '2024-01-23',
  },
  {
    id: '10',
    nama: 'Joko Susilo',
    nomor_sertif: 'CERT-2024-010',
    asal: 'Dinas Perdagangan',
    kab_kot: 'Kediri',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-24',
    updatedAt: '2024-01-24',
  },
  {
    id: '11',
    nama: 'Karina Mulia',
    nomor_sertif: 'CERT-2024-011',
    asal: 'PT Manufaktur Industri',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-25',
    updatedAt: '2024-01-25',
  },
  {
    id: '12',
    nama: 'Lestari Indah',
    nomor_sertif: 'CERT-2024-012',
    asal: 'Universitas Negeri',
    kab_kot: 'Malang',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-26',
    updatedAt: '2024-01-26',
  },
  {
    id: '13',
    nama: 'Makmur Hasan',
    nomor_sertif: 'CERT-2024-013',
    asal: 'PT Logistik Cepat',
    kab_kot: 'Pasuruan',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-27',
    updatedAt: '2024-01-27',
  },
  {
    id: '14',
    nama: 'Nurul Azizah',
    nomor_sertif: 'CERT-2024-014',
    asal: 'Balai Pelatihan',
    kab_kot: 'Blitar',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-01-28',
    updatedAt: '2024-01-28',
  },
  {
    id: '15',
    nama: 'Okto Prawira',
    nomor_sertif: 'CERT-2024-015',
    asal: 'PT Media Komunikasi',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-29',
    updatedAt: '2024-01-29',
  },
  {
    id: '16',
    nama: 'Putri Handayani',
    nomor_sertif: 'CERT-2024-016',
    asal: 'CV Jasa Konsultasi',
    kab_kot: 'Jombang',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-30',
    updatedAt: '2024-01-30',
  },
  {
    id: '17',
    nama: 'Quirino Santiago',
    nomor_sertif: 'CERT-2024-017',
    asal: 'PT Perdagangan Global',
    kab_kot: 'Nganjuk',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-01-31',
    updatedAt: '2024-01-31',
  },
  {
    id: '18',
    nama: 'Ratna Dewi',
    nomor_sertif: 'CERT-2024-018',
    asal: 'Yayasan Pendidikan',
    kab_kot: 'Bojonegoro',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: '19',
    nama: 'Sintha Purwati',
    nomor_sertif: 'CERT-2024-019',
    asal: 'PT Pertanian Modern',
    kab_kot: 'Ponorogo',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-02-02',
    updatedAt: '2024-02-02',
  },
  {
    id: '20',
    nama: 'Teguh Setiawan',
    nomor_sertif: 'CERT-2024-020',
    asal: 'Pemerintah Daerah',
    kab_kot: 'Madiun',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-03',
    updatedAt: '2024-02-03',
  },
  {
    id: '21',
    nama: 'Utami Sukesi',
    nomor_sertif: 'CERT-2024-021',
    asal: 'PT Retail Terpadu',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-04',
    updatedAt: '2024-02-04',
  },
  {
    id: '22',
    nama: 'Vidi Santoso',
    nomor_sertif: 'CERT-2024-022',
    asal: 'PT Teknologi Cloud',
    kab_kot: 'Malang',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-05',
    updatedAt: '2024-02-05',
  },
  {
    id: '23',
    nama: 'Wulan Setyowati',
    nomor_sertif: 'CERT-2024-023',
    asal: 'Klinik Kesehatan',
    kab_kot: 'Sidoarjo',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-06',
    updatedAt: '2024-02-06',
  },
  {
    id: '24',
    nama: 'Xander Maulana',
    nomor_sertif: 'CERT-2024-024',
    asal: 'PT Konstruksi Besar',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-02-07',
    updatedAt: '2024-02-07',
  },
  {
    id: '25',
    nama: 'Yuni Hastuti',
    nomor_sertif: 'CERT-2024-025',
    asal: 'Kantor Notaris',
    kab_kot: 'Gresik',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-08',
    updatedAt: '2024-02-08',
  },
  {
    id: '26',
    nama: 'Zainudin Rafiq',
    nomor_sertif: 'CERT-2024-026',
    asal: 'PT Automotive Parts',
    kab_kot: 'Lamongan',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-09',
    updatedAt: '2024-02-09',
  },
  {
    id: '27',
    nama: 'Adie Rahman',
    nomor_sertif: 'CERT-2024-027',
    asal: 'PT Furniture Export',
    kab_kot: 'Jepara',
    provinsi: 'Jawa Tengah',
    status: 'Aktif',
    createdAt: '2024-02-10',
    updatedAt: '2024-02-10',
  },
  {
    id: '28',
    nama: 'Bambang Irawan',
    nomor_sertif: 'CERT-2024-028',
    asal: 'CV Elektronik Murah',
    kab_kot: 'Bandung',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-11',
    updatedAt: '2024-02-11',
  },
  {
    id: '29',
    nama: 'Camelia Putri',
    nomor_sertif: 'CERT-2024-029',
    asal: 'PT Tekstil Indonesia',
    kab_kot: 'Bandung',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-12',
    updatedAt: '2024-02-12',
  },
  {
    id: '30',
    nama: 'Danang Wijaya',
    nomor_sertif: 'CERT-2024-030',
    asal: 'PT Farmasi Maju',
    kab_kot: 'Jakarta',
    provinsi: 'DKI Jakarta',
    status: 'Tidak Aktif',
    createdAt: '2024-02-13',
    updatedAt: '2024-02-13',
  },
  {
    id: '31',
    nama: 'Erika Maharani',
    nomor_sertif: 'CERT-2024-031',
    asal: 'Universitas Trisakti',
    kab_kot: 'Jakarta',
    provinsi: 'DKI Jakarta',
    status: 'Aktif',
    createdAt: '2024-02-14',
    updatedAt: '2024-02-14',
  },
  {
    id: '32',
    nama: 'Farhan Azmi',
    nomor_sertif: 'CERT-2024-032',
    asal: 'PT Keuangan Digital',
    kab_kot: 'Jakarta',
    provinsi: 'DKI Jakarta',
    status: 'Aktif',
    createdAt: '2024-02-15',
    updatedAt: '2024-02-15',
  },
  {
    id: '33',
    nama: 'Ginanjar Kurnia',
    nomor_sertif: 'CERT-2024-033',
    asal: 'PT Layanan Asuransi',
    kab_kot: 'Bogor',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-16',
    updatedAt: '2024-02-16',
  },
  {
    id: '34',
    nama: 'Hilda Nurjana',
    nomor_sertif: 'CERT-2024-034',
    asal: 'CV Desain Grafis',
    kab_kot: 'Bandung',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-17',
    updatedAt: '2024-02-17',
  },
  {
    id: '35',
    nama: 'Indra Mulyadi',
    nomor_sertif: 'CERT-2024-035',
    asal: 'PT Telekomunikasi',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-18',
    updatedAt: '2024-02-18',
  },
  {
    id: '36',
    nama: 'Jasmine Lestari',
    nomor_sertif: 'CERT-2024-036',
    asal: 'Bank Pemerintah',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-02-19',
    updatedAt: '2024-02-19',
  },
  {
    id: '37',
    nama: 'Kenji Tanaka',
    nomor_sertif: 'CERT-2024-037',
    asal: 'Perusahaan Swasta Jepang',
    kab_kot: 'Jakarta',
    provinsi: 'DKI Jakarta',
    status: 'Aktif',
    createdAt: '2024-02-20',
    updatedAt: '2024-02-20',
  },
  {
    id: '38',
    nama: 'Linda Kusuma',
    nomor_sertif: 'CERT-2024-038',
    asal: 'PT Operator Logistik',
    kab_kot: 'Serpong',
    provinsi: 'Banten',
    status: 'Aktif',
    createdAt: '2024-02-21',
    updatedAt: '2024-02-21',
  },
  {
    id: '39',
    nama: 'Made Arta',
    nomor_sertif: 'CERT-2024-039',
    asal: 'PT Properti Besar',
    kab_kot: 'Denpasar',
    provinsi: 'Bali',
    status: 'Aktif',
    createdAt: '2024-02-22',
    updatedAt: '2024-02-22',
  },
  {
    id: '40',
    nama: 'Nadia Khalifa',
    nomor_sertif: 'CERT-2024-040',
    asal: 'PT Kebersihan Lingkungan',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-23',
    updatedAt: '2024-02-23',
  },
  {
    id: '41',
    nama: 'Omar Fakhri',
    nomor_sertif: 'CERT-2024-041',
    asal: 'PT Minyak Persada',
    kab_kot: 'Balikpapan',
    provinsi: 'Kalimantan Timur',
    status: 'Aktif',
    createdAt: '2024-02-24',
    updatedAt: '2024-02-24',
  },
  {
    id: '42',
    nama: 'Priya Rathod',
    nomor_sertif: 'CERT-2024-042',
    asal: 'PT Teknologi India',
    kab_kot: 'Bangalore',
    provinsi: 'Karnataka',
    status: 'Tidak Aktif',
    createdAt: '2024-02-25',
    updatedAt: '2024-02-25',
  },
  {
    id: '43',
    nama: 'Qasim Hariri',
    nomor_sertif: 'CERT-2024-043',
    asal: 'PT Perdagangan Arab',
    kab_kot: 'Jakarta',
    provinsi: 'DKI Jakarta',
    status: 'Aktif',
    createdAt: '2024-02-26',
    updatedAt: '2024-02-26',
  },
  {
    id: '44',
    nama: 'Rina Wijaya',
    nomor_sertif: 'CERT-2024-044',
    asal: 'CV Catering Makanan',
    kab_kot: 'Malang',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-02-27',
    updatedAt: '2024-02-27',
  },
  {
    id: '45',
    nama: 'Suryanto Hermawan',
    nomor_sertif: 'CERT-2024-045',
    asal: 'PT Otomotif Mobil',
    kab_kot: 'Karawang',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-28',
    updatedAt: '2024-02-28',
  },
  {
    id: '46',
    nama: 'Tuti Hendarsih',
    nomor_sertif: 'CERT-2024-046',
    asal: 'PT Minuman Sehat',
    kab_kot: 'Bandung',
    provinsi: 'Jawa Barat',
    status: 'Aktif',
    createdAt: '2024-02-29',
    updatedAt: '2024-02-29',
  },
  {
    id: '47',
    nama: 'Umar Saleh',
    nomor_sertif: 'CERT-2024-047',
    asal: 'PT Mesin Industri',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
  {
    id: '48',
    nama: 'Vera Sundari',
    nomor_sertif: 'CERT-2024-048',
    asal: 'Koperasi Simpan Pinjam',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Tidak Aktif',
    createdAt: '2024-03-02',
    updatedAt: '2024-03-02',
  },
  {
    id: '49',
    nama: 'Wendra Prayitno',
    nomor_sertif: 'CERT-2024-049',
    asal: 'PT Transportasi Bus',
    kab_kot: 'Surabaya',
    provinsi: 'Jawa Timur',
    status: 'Aktif',
    createdAt: '2024-03-03',
    updatedAt: '2024-03-03',
  },
  {
    id: '50',
    nama: 'Xenia Sophia',
    nomor_sertif: 'CERT-2024-050',
    asal: 'PT Perhotelan Bintang',
    kab_kot: 'Bali',
    provinsi: 'Bali',
    status: 'Aktif',
    createdAt: '2024-03-04',
    updatedAt: '2024-03-04',
  },
];

// ─── Profile ───────────────────────────────────────────────────────────────

export const mockProfile: ProfileData = {
  id: '1',
  name: 'Admin',
  email: 'admin@gmail.com',
  phone: '+62 812 3456 7890',
  institution: 'IGI JATIM',
  createdAt: '2024-01-01',
  updatedAt: new Date().toISOString(),
};

// ─── Settings ────────────────────────────────────────────────────────────────

export const mockSettings: AppSettings = {
  theme: 'light',
  language: 'id',
  emailNotifications: true,
  uploadNotifications: true,
};

export const mockGoogleSheetsSettings: GoogleSheetsSettings = {
  spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
  sheetName: 'Sertifikat',
  range: 'A1:G1000',
  syncInterval: 60,
  enabled: true,
};

// ─── Certificate Templates ─────────────────────────────────────────────────

export const mockCertificateTemplates: CertificateTemplate[] = [
  {
    id: 'default',
    name: 'Desain Bawaan',
    type: 'default',
    description: 'Template sertifikat klasik dengan ornamen Indonesia',
  },
  {
    id: 'custom-vibrant',
    name: 'Desain Vibrant',
    type: 'custom',
    description: 'Template modern dengan warna vibrant dan gradasi',
  },
];

export const defaultCertificateLayout: CertificateLayout = {
  preset: 'standard',
  titlePosition: { x: 50, y: 20 },
  namePosition: { x: 50, y: 45 },
  numberPosition: { x: 50, y: 60 },
  datePosition: { x: 50, y: 75 },
  signaturePosition: { x: 70, y: 85 },
  fontSize: 18,
  fontFamily: 'serif',
};

// ─── Certificate Preview Data ──────────────────────────────────────────────

export const mockCertificatePreview: CertificatePreviewData = {
  sertifikat: mockSertifikats[0],
  template: mockCertificateTemplates[0],
  layout: defaultCertificateLayout,
};
